[project]
name = "kodi-cli"
version = "0.2.6"
description = "Control your Kodi instance(s) via the commandline"
authors = [
    {name = "Al D'Amico",email = "JavaWiz1@hotmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "loguru"
]

[tool.poetry.scripts]
kodi-cli = "kodi_cli.driver:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
